### ISSUE TITLE
PHP path info does not work

### ISSUE THREAD

**Issue by char101** [valentinxxx/nginxconfig.io#44]
In `php_fastcgi.conf` there is this rule `fastcgi_split_path_info		^(.+\.php)(/.+)$;` which does not work because the location regex only matches `\.php$`.

It will be more useful to match `[^/]\.php(/|$)` in the location regex.

**Comment by char101** [comment]
Also with path info, this line `try_files $uri =404;` on top of `php_fastcgi.conf` does not work because `$uri` may not point to a real path.

**Comment by char101** [comment]
Alternatively to check the existence of the file

```
if (!-f $document_root$fastcgi_script_name) {
    return 404;
}
```

**Comment by char101** [comment]
Also this line is required in `php_fastcgi.conf`

```
fastcgi_param				PATH_INFO       $fastcgi_path_info;
```

**Comment by valentinxxx** [comment]
It works perfectly fine for me.
(Maybe you've skipped the index.php fallback?)

If you check the major PHP frameworks' nginx documentation:
- https://laravel.com/docs/5.7/deployment#nginx
- https://symfony.com/doc/current/setup/web_server_configuration.html#nginx
- https://www.yiiframework.com/doc/guide/1.1/en/quickstart.apache-nginx-config#nginx

You will see only the `fastcgi_split_path_info ^(.+\.php)(/.*)$;` is required, everything else is defined in the stock `fastcgi_params` file.

`try_files $uri =404;` is needed for handling a non existing php file with nginx 404 error page rather than PHP-FPM's `No input file specified.` message.

Also [If Is Evil](https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/), [nginxconfig.io](https://nginxconfig.io) does not use any `if` in configurations.

**Comment by valentinxxx** [comment]
Now I understand your issue with `try_files`.
I was preparing the Magento support and there is the following URL structure for setup: `/setup/index.php/navigation`.
The `try_files` failed, so I've moved it from `php_fastcgi.conf` to `location ~ \.php$ {}`, so it can be overridden.

**Comment by char101** [comment]
Hmm I don't know, it seems to me that this regex `\.php$` will not match e.g. `/index.php/some/path/info`, will it?

By the way, I encountered the problem when installing moodle.

As for the frameworks documentation, it does not uses path info, the route is passed as a query string as you can see in this line `try_files $uri $uri/ /index.php?$query_string`. Older PHP applications still uses `index.php` in the URL, which is why the part after `\.php` still need to be matched to support path info in the URL.

**Comment by char101** [comment]
Example from nginx website:

```
location ~ [^/]\.php(/|$) {
    fastcgi_split_path_info ^(.+?\.php)(/.*)$;
    if (!-f $document_root$fastcgi_script_name) {
        return 404;
    }

    # Mitigate https://httpoxy.org/ vulnerabilities
    fastcgi_param HTTP_PROXY "";

    fastcgi_pass 127.0.0.1:9000;
    fastcgi_index index.php;

    # include the fastcgi_param setting
    include fastcgi_params;

    # SCRIPT_FILENAME parameter is used for PHP FPM determining
    #  the script name. If it is not set in fastcgi_params file,
    # i.e. /etc/nginx/fastcgi_params or in the parent contexts,
    # please comment off following line:
    # fastcgi_param  SCRIPT_FILENAME   $document_root$fastcgi_script_name;
}
```

**Comment by valentinxxx** [comment]
Thanks for your inputs @char101!

I've made a lot of research in this topic and commited (https://github.com/valentinxxx/nginxconfig.io/commit/c25228ef536fe2b61f4295609a014bc9705bd4d5) the `Legacy PHP routing` option.
It utilises the `fastcgi_split_path_info` directive and `PATH_INFO` param only if enabled.

Also made a PR to Laravel docs in this topic: https://github.com/laravel/docs/pull/4847
