### ISSUE TITLE
sed command for disabling SSL directives leaves redirect to ssl site active

### ISSUE THREAD

**Issue by serverbrain** [valentinxxx/nginxconfig.io#53]
First: *very* nice project! Thank you very much for giving the world this tool! 

Only very little room for optimization: 

The sed command for disabling SSL directives leaves the redirect to the ssl site active. 

Nice holidays!

**Comment by valentinxxx** [comment]
There is a `include nginxconfig.io/letsencrypt.conf;` line in the HTTP server block.
It includes the following location block:
```nginx
location ^~ /.well-known/acme-challenge/ {
	root /var/www/_letsencrypt;
}
```

Your issue is about the following block:
```nginx
location / {
	return 301 https://example.com$request_uri;
}
```

The ACME-challenge route has higher precedence than the redirect one, so the challenge will not be affected by the redirection.

Btw. disabling the SSL directives is only necessary because the missing certificate files will cause nginx error.
