### ISSUE TITLE
no host in ":80" of the "listen" directive

### ISSUE THREAD

**Issue by sherif84** [valentinxxx/nginxconfig.io#65]
Hi,
i'm using this configuration for a reverse proxy: 
https://nginxconfig.io/?0.domain=sample.app.com&0.ipv4=&0.https=false&0.php=false&0.proxy&0.proxy_pass=http:%2F%2Fsampleapp:5000&0.root=false&0.access_log_domain&0.error_log_domain

when applying to nginx , i get the following error 

nginx: [emerg] no host in ":80" of the "listen" directive in /etc/nginx/sites-enabled/sample.app.com.conf:2

if i manually change all instances of "listen :80;" to "listen 80;" removing the ":" it works fine.

is there something I'm missing that i need to configure ? or an nginx version compatibility?

nginx version: nginx/1.14.2

**Comment by valentinxxx** [comment]
It's because you've changed the `IPv4` field's value from the default `*` to an empty string.
If you reset it, everything works: https://nginxconfig.io/?0.domain=sample.app.com&0.https=false&0.php=false&0.proxy&0.proxy_pass=http:%2F%2Fsampleapp:5000&0.root=false&0.access_log_domain&0.error_log_domain
